apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-redis
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: quay.io/h0tbird/tva-redis:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: redis-tva
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
